### ISSUE TITLE
[Feature] Screenshot Download option

### ISSUE THREAD

**Issue by gitgoap** [gitgoap/AI-Snipping-Tool#26]
- Need to add a button beside other buttons to download the screenshot captured.
- Download will be saved in the local system.

**Comment by kapilG0** [comment]
Hello @gitgoap please assign this issue to me

**Comment by gitgoap** [comment]
@kapilG0 go for it!

**Comment by gitgoap** [comment]
@kapilG0 Any update on the work?

**Comment by apoorvsxna** [comment]
Can I take up this issue? @gitgoap

**Comment by gitgoap** [comment]
@apoorvsxna 
Assigned!
