### ISSUE TITLE
[UI update]: Need a better mockup of extension popup

### ISSUE THREAD

**Issue by gitgoap** [gitgoap/AI-Snipping-Tool#3]
# UI change of the popup of the extension

- This is an open issue anyone can raise PR if they have a good UI design
- Make sure to put your design in https://github.com/gitgoap/AI-Snipping-Tool/tree/main/New%20UI%20designs Dir while raising PR

### Take inspiration from the below example
![image](https://github.com/gitgoap/AI-Snipping-Tool_IIT-D_Hackathon/assets/117789470/ec1b5a2f-aa1e-45ee-9ad1-ab584a54aea3)

**Comment by Nirvanjha2004** [comment]
Please assign me this issue

**Comment by gitgoap** [comment]
@sakshi261203 
Go for it!
Make sure to raise P.R. on or after 1st of June to get SSOC points.

**Comment by gitgoap** [comment]
@sakshi261203 
Go for it!
Make sure to raise P.R. on or after the 1st of June to get SSOC points.

**Comment by gitgoap** [comment]
@sakshi261203 what is the status of the work?

**Comment by sakshi261203** [comment]
I'm sorry to say, but because of some problems I am unable to work on that issue now...

**Comment by gitgoap** [comment]
sakshi261203: I am unassigning this issue.

Anyone want to take up this issue comment while **tagging me**.

**Comment by SRB1025X** [comment]
@gitgoap please assign me this issue....i have some UI experience for android apps

**Comment by gitgoap** [comment]
@SRB1025X 
Assigned
But remember this is a _chrome extension not a mobile app._

**Suggestion**: Install our chrome extension once, use it once or twice and then make the prototype UI.

**Comment by gitgoap** [comment]
@SRB1025X Any updates on the issue

**Comment by SRB1025X** [comment]
@gitgoap working on it.... Give me 2-3 days

**Comment by gitgoap** [comment]
@SRB1025X  To get points for this issue, just put the UI mockup in a new folder/dir in this repo while raising a PR

**Comment by gitgoap** [comment]
> @gitgoap working on it.... Give me 2-3 days

Take your time

**Comment by gitgoap** [comment]
@SRB1025X 
give me update of your work

**Comment by SRB1025X** [comment]
created a PR just now....please review
