### ISSUE TITLE
Adding a save option.

### ISSUE THREAD

**Issue by Chelseasingla1** [gitgoap/AI-Snipping-Tool#35]
### Add a feature where users can save notes or texts.
**Optional for user**: No compulsion for users to use this feature
 The text needs to be saved in the a `.txt file` in local system.

**Comment by hitesh-mehta** [comment]
please assign it to me

**Comment by gitgoap** [comment]
@hitesh-mehta 
Read the instructions carefully in the description and then add this feature.
You are assigned.

**Comment by gitgoap** [comment]
@hitesh-mehta What's the status

**Comment by apoorvsxna** [comment]
I'd like to work on this.

**Comment by gitgoap** [comment]
@apoorvsxna Assigned!
