### ISSUE TITLE
[Feat] Integration with Gemini AI LLM to summarize the extracted text

### ISSUE THREAD

**Issue by hitesh-mehta** [gitgoap/AI-Snipping-Tool#40]
- We need to integrate the model with a script using gemini  model to summarize the extracted text.
- Suggest to put a summarize button in the extension popup 
-  everyone will have option to put their own Gemini API key

**Comment by gitgoap** [comment]
@hitesh-mehta 
Please write details in the description of the issue you wish to be implemented.

I suggest to put a summarize button in the extension popup and everyone will have option to put their own Gemini API key

**Comment by apoorvsxna** [comment]
Hey there. I would like to take up this issue. I have implemented a similar feature in one of my projects previously, and am familiar with how it could be added here.
Could you assign this issue to me? Thanks!

**Comment by gitgoap** [comment]
@apoorvsxna 
Go for it!

**Comment by hitesh-mehta** [comment]
For the easy usability of the extension, I suggest that a single popup button to summarize must appear that should directly request the Gemini based server to summarize the data extracted and fetch it back to the user. The feature to put in the user specific Gemini API key makes it cumbersome for some users to process! If the maintainers still want the same, I can do that as well. Please assign the issue to me.

**Comment by gitgoap** [comment]
@apoorvsxna 
What's the update on this issue

**Comment by gitgoap** [comment]
> For the easy usability of the extension, I suggest that a single popup button to summarize must appear that should directly request the Gemini based server to summarize the data extracted and fetch it back to the user. The feature to put in the user specific Gemini API key makes it cumbersome for some users to process! If the maintainers still want the same, I can do that as well. Please assign the issue to me.

The reason for putting a user specific API key is since the Gemini API is not free after 60 requests per minute so if more requests than this limit is made through my API key then I have to bear the cost.

Also, there is no source of monetization.

**Comment by apoorvsxna** [comment]
> @apoorvsxna 
> What's the update on this issue 

I am close to completion. I'll probably make a pull request by tonight.

**Comment by apoorvsxna** [comment]
Hey man @gitgoap . Apologies for the delay. Was running into some issues when integrating the Gemini API using the [quickstart guide](https://ai.google.dev/gemini-api/docs/quickstart?lang=web) as it requires using import maps which are only supported through inline JS, and chrome doesn't allow extensions to run inline scripts.
I managed to find a workaround by making a direct fetch request instead, based on details in the [cURL method](https://ai.google.dev/gemini-api/docs/api-overview).
