### ISSUE TITLE
[Feature] Gemini related: Adding a user defined prompt option  instead of summary button

### ISSUE THREAD

**Issue by gitgoap** [gitgoap/AI-Snipping-Tool#48]
# --- Feature ---

## Background
Check **Pull Request: #47**  
- It integrated the Gemini API into this extension for summarization. 
- In file `element.js` under `inject` directory `line no. 735` has prompt **Summarize the following in simple words-** {*Refer below Image*}

![Screenshot 2024-06-12 220749](https://github.com/gitgoap/AI-Snipping-Tool/assets/117789470/299d721b-aac1-45b9-8b7a-70612924c47f)

## Main feature to build

- Need to remove the `summarize` button.
- Need to put an input space where the user-defined prompt will be put. Similar to API input field.
- Either add an `ENTER` button or on user click of enter from the keyboard in the `prompt input field` the user-defined prompt is sent to Google Gemini for a response.
![image](https://github.com/gitgoap/AI-Snipping-Tool/assets/117789470/fe26d9a5-b52f-4475-bf33-f2c3ff032c55)

**Comment by apoorvsxna** [comment]
I could follow up on my previous PR and introduce this feature as well.
I've also noticed a resizing issue in the extension when changing the size of the browser window/tab. I'll fix that when I add the new input field.

**Comment by gitgoap** [comment]
Assigned @apoorvsxna
