### ISSUE TITLE
[UI/UX] Enhance the colour and size of chrome extension popup

### ISSUE THREAD

**Issue by gitgoap** [gitgoap/AI-Snipping-Tool#50]
- Update the current `colour` of the extension to look better.
- Update the `size` of the space input and the size of the text that appears.

**Comment by anaritadauane** [comment]
Hi there!

Please can you assign this to me?

**Comment by gitgoap** [comment]
@anaritadauane Assigned!
Make sure to use better combination of colors and test it robustly.

**Comment by anaritadauane** [comment]
Thank you! 
I'm on it
