### ISSUE TITLE
[Feature] Option to save Gemini API key in the browser

### ISSUE THREAD

**Issue by gitgoap** [gitgoap/AI-Snipping-Tool#51]
# Saving of Google Gemini API Key in the browser

## Background
- This extension has a feature through will we can put Gemini API and ask questions from the text extracted {See P.R. #48}
- But putting API each time after taking the screenshot is **hectic**

## Proposal
- You should put a button on the extension that gives users the option if they want to save the API key or not.
- The next time the user uses the extension then the API key should be autofilled in the API space bar.

**Comment by vishalmaurya850** [comment]
Assign this issue to me

**Comment by gitgoap** [comment]
@vishalmaurya850  Go for it!

**Comment by gitgoap** [comment]
@vishalmaurya850 Any updates?

**Comment by vishalmaurya850** [comment]
API is secret key for someone why You want to save it in browser it will affect his/her personal details

**Comment by vishalmaurya850** [comment]
Please tell

**Comment by apoorvsxna** [comment]
> API is secret key for someone why You want to save it in browser it will affect his/her personal details

The main reason would be to make the usage more convenient by not having to enter it each time the Gemini has to be used.
Also, the key will only be stored locally on the user's browser and so, it would not be a privacy issue.
Am I right? @gitgoap

**Comment by vishalmaurya850** [comment]
Also tell how to merge as I have the code?

**Comment by gitgoap** [comment]
> > API is secret key for someone why You want to save it in browser it will affect his/her personal details
> 
> The main reason would be to make the usage more convenient by not having to enter it each time the Gemini has to be used.
> Also, the key will only be stored locally on the user's browser and so, it would not be a privacy issue.
> Am I right? @gitgoap 

👍🏻 Right

**Comment by gitgoap** [comment]
> Also tell how to merge as I have the code?
Commit and push the code.
I'll merge it if your code is good.

**Comment by gitgoap** [comment]
@vishalmaurya850 you haven't pushed the code in gitgoap repo, you have merged the code in your forked repo.

When you raise a PR then it will appear here https://github.com/gitgoap/AI-Snipping-Tool/pulls

**Comment by vishalmaurya850** [comment]
Now it's ok??

**Comment by vishalmaurya850** [comment]
Is that working?

**Comment by gitgoap** [comment]
> Is that working?

Please do any conversation in your PR raised i.e #63 
Since it just clutters and makes it difficult for other contributors to review the issue.

**Comment by apoorvsxna** [comment]
Can I take up this issue now that it has been unassigned?
@gitgoap

**Comment by gitgoap** [comment]
@apoorvsxna sure
