### ISSUE TITLE
[doc] Updation of image from readme file

### ISSUE THREAD

**Issue by gitgoap** [gitgoap/AI-Snipping-Tool#52]
![image](https://github.com/gitgoap/AI-Snipping-Tool/assets/117789470/8e928859-247b-4e57-b7f1-9439bc1e37e4)
- Update above image in the readme file with a similar but `much better` coding example image.
- Keep the dimension of image near to same as before

**Comment by kapilG0** [comment]
Hello @gitgoap please assign this issue to me

**Comment by gitgoap** [comment]
Kapil 
You are assigned #26 so complete that issue first before you get another issue assigned.

**Comment by meetalik8** [comment]
Hello @gitgoap can you assign this issue to me? I would like to work on this. Thanks!

**Comment by gitgoap** [comment]
@meetalik8 Go for it!
