### ISSUE TITLE
[Doc] Remove emoji from the last line of contributor guide file

### ISSUE THREAD

**Issue by gitgoap** [gitgoap/AI-Snipping-Tool#53]
![image](https://github.com/gitgoap/AI-Snipping-Tool/assets/117789470/7c0c92de-ec8d-4e91-836b-87bcc6eaa52f)
- Remove the emojis present in the image from contributor.md file

**Comment by AnClicks** [comment]
@gitgoap kindly assign me this issue.

**Comment by Manish15559** [comment]
hello @gitgoap 
can u assign this issue to me

**Comment by gitgoap** [comment]
@AnClicks assigned!

**Comment by RishiSharmapro** [comment]
Hello @gitgoap 
I would like to work on this issue, please assign it to me :)
