### ISSUE TITLE
[Feature] Dark mode of the extension

### ISSUE THREAD

**Issue by gitgoap** [gitgoap/AI-Snipping-Tool#57]
# Dark Mode
- Need to put dark mode in this chrome extension
## Points to remember

- Put a dark mode toggle button.
- Make sure the button doesn't make the overall UI bad
- Test robust in chrome as well as in brave browser.

**Comment by TanviGandhotra** [comment]
assign me plz

**Comment by karan-panda** [comment]
### Please assign it to me
I have experience in such tasks!!

**Comment by gitgoap** [comment]
@TanviGandhotra 
Assigned!

**Comment by gitgoap** [comment]
@TanviGandhotra 
Any updates!

**Comment by TanviGandhotra** [comment]
will push it before 11 pm .

**Comment by gitgoap** [comment]
@karan-panda
Do you want to take this issue?

**Comment by karan-panda** [comment]
Yeah, I can take this issue. 
But I will be able to make the changes after Saturday evening😅, as I am a little busy with college and internship.

**Comment by TanviGandhotra** [comment]
Due to some family issue I will not be able to work on this.. srry for this inconvience . I want you to give this issue to other person.

**Comment by gitgoap** [comment]
> Yeah, I can take this issue. But I will be able to make the changes after Saturday evening😅, as I am a little busy with college and internship.

No problem take your time.
I am assigning you this issue.

**Comment by gitgoap** [comment]
@karan-panda Any status

**Comment by karan-panda** [comment]
Still working on it. I will complete it soon. 
I will try to put the PR by tonight or tomorrow morning.

**Comment by karan-panda** [comment]
@gitgoap Great news! The task is complete. I've successfully added dark mode and implemented local storage for remembering user preferences. I'll proceed to raise the PR now.

**Comment by gitgoap** [comment]
> @gitgoap Great news! The task is complete. I've successfully added dark mode and implemented local storage for remembering user preferences. I'll proceed to raise the PR now.

Can you describe a little how/what kind of local storage you added.

**Comment by karan-panda** [comment]
Sure! I implemented local storage to store the user's preferred mode selection (light or dark). When the user changes the mode, their choice is saved locally in the browser. This way, the next time they visit the page, it remembers their last selected mode and applies it automatically.
