### ISSUE TITLE
[Bug] Snipping Tool not working over the github side panel

### ISSUE THREAD

**Issue by gitgoap** [gitgoap/AI-Snipping-Tool#59]
- Refer to the below video, this extension doesn't work when the cursor hovers over the **side panel**
- Find a fix
- Also check if it happens in other websites' side panels.

https://github.com/gitgoap/AI-Snipping-Tool/assets/117789470/77c7242b-f023-415d-8370-b4515ca1ecbf

**Comment by vishalmaurya850** [comment]
Assign this issue to me

**Comment by gitgoap** [comment]
> But I can provide you the python code for the selenium library

This extension don't support python

**Comment by vishalmaurya850** [comment]
Which extension your code or selenium?

**Comment by apoorvsxna** [comment]
I think this has been resolved after the redesign. Can you confirm? @gitgoap

**Comment by gitgoap** [comment]
@apoorvsxna Yes! It is resolved. What was the problem causing it?

**Comment by apoorvsxna** [comment]
I am not sure about what was causing it to be honest, but it has been fixed.
