### ISSUE TITLE
(UI Update) Redesign extension according to updated mockup

### ISSUE THREAD

**Issue by apoorvsxna** [gitgoap/AI-Snipping-Tool#70]
# UI Update
- An updated mockup consisting of the new features was recently introduced. Refer to this [PR](https://github.com/gitgoap/AI-Snipping-Tool/issues/3) for context.
- This means that a complete renovation of the extension interface is required.
- The existing functionality should remain the same and the popup should be responsive (flexible to adjust according to various screen sizes).
- The mockup can be found in the `New UI Designs` folder.

**Comment by apoorvsxna** [comment]
Hi @gitgoap, could you add the suitable labels to this issue?
Also, I'd like to get assigned to this issue and start working on it. Thanks!

**Comment by gitgoap** [comment]
@apoorvsxna 
Go for it!
Also, the new UI proposed lacks several buttons and space for text. So keep this in mind.

**Comment by gitgoap** [comment]
@apoorvsxna Join [oslead site](https://www.oslead.xyz/) so that I can assign you points for previous PRs
and what's the status on this one
