### ISSUE TITLE
[BUG] Text not visible

### ISSUE THREAD

**Issue by gitgoap** [gitgoap/AI-Snipping-Tool#72]
## Background colour and text colour matching resulting in less visibility
 - Bug in light mode
 - Present in both `OCR Text` & `Prompt response` space

## Potential fix
- Either change the colour of  the `text` or  the `background`
- Fix needed in light mode
- Both section
   
![image](https://github.com/user-attachments/assets/a4bf2e80-a4d8-40da-9070-e21b0e4c0b50)

**Comment by ashish111333** [comment]
Can i work on this?

**Comment by gitgoap** [comment]
go for it!
@ashish111333 

Make sure to clone the repo properly, if need any help ask me.
