### ISSUE TITLE
[Bug] Close text in popup not appearing in one line

### ISSUE THREAD

**Issue by gitgoap** [gitgoap/AI-Snipping-Tool#73]
## Top Right of popup

`Close` text not present in one line.

![image](https://github.com/user-attachments/assets/e27cc189-94a7-4d8f-92d1-42deffc1f088)

**Comment by akarshghildyal** [comment]
Hello I would like to work on this under SSOC

**Comment by gitgoap** [comment]
Go for it!
@akarshghildyal 

Make sure to clone the repo properly, if need any help ask me.

**Comment by akarshghildyal** [comment]
> Go for it!
> @akarshghildyal 
> 
> Make sure to clone the repo properly, if need any help ask me.

yessir, will do.
