### ISSUE TITLE
[Doc] Update screenshots of new ui of extension popup in read me

### ISSUE THREAD

**Issue by gitgoap** [gitgoap/AI-Snipping-Tool#74]
## Guidelines to update readme
- 3 screenshots need to be added as given in [READ ME](https://github.com/gitgoap/AI-Snipping-Tool/blob/main/README.md)
- New UI of chrome extension popup screenshot must be taken on the [Wikipedia main page](https://www.wikipedia.org), similar to old 
   screenshots.
- Size of the screenshot should be such that text is clearly visible and the screenshot don't look too big.
  ***follow this format***
```
<img src ="https://github.com/gitgoap/AI-Snipping-Tool/assets/117789470/f1c582bc-2222-4d4f-8941-689da9e517cc" height= 500 >
```
- Screenshots should be `well cropped` 
-  Put your own `API KEY` from Google AI Studio and ask the same question asked in old screenshot present in readme currently.
![image](https://github.com/user-attachments/assets/603e38fb-bc46-4edc-9f66-4e9189c405fe)

**Comment by Sat-Star** [comment]
Hello, I would like to solve this issue under SSOC

**Comment by gitgoap** [comment]
@Sat-Star Go for it!

**Comment by Sat-Star** [comment]
I have replaced the screenshots and opened a pull request. Please check

**Comment by rbchettri1** [comment]
Was this issue resolved or is it still open?

**Comment by gitgoap** [comment]
@rbchettri1 
New screenshots are needed as the extension got a new update so you can work on this issue.

**Comment by gitgoap** [comment]
@apoorvsxna do it
