### ISSUE TITLE
[Tech Update] For saving API key: Migration to Chrome Storage API from localStorage 

### ISSUE THREAD

**Issue by gitgoap** [gitgoap/AI-Snipping-Tool#79]
## Background

- AI Snipping Tool uses `localStorage` feature to save the Gemini API key in Chrome.
- [P.R. 77] (https://github.com/gitgoap/AI-Snipping-Tool/pull/77) This PR created the functionality for saving the API key with localStorage.
- Since handling API keys safely is most important for any project.
- localStorage ***isn't very secure.***

## Changes Needed
- Proposing to change the technology to save the Gemini API key from `localStorage` to `Chrome Storage API.

## [Read local storage docs](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage)

**Comment by gitgoap** [comment]
> I was doing that only but you unassigned me

You were taking too long to solve the issue. Other participants of SSOC should get a fair chance of solving the issue. That is why I unassigned.

**Comment by vishalmaurya850** [comment]
Ok let's see who solves this issue.

**Comment by apoorvsxna** [comment]
I'd like to take up this issue @gitgoap .

**Comment by gitgoap** [comment]
@apoorvsxna assigned

**Comment by apoorvsxna** [comment]
I've created a pull request for this issue. Do let me know if any changes are required. @gitgoap
