### ISSUE TITLE
(Feature) Add button to get Gemini API Key

### ISSUE THREAD

**Issue by apoorvsxna** [gitgoap/AI-Snipping-Tool#85]
- For new users who are not familiar with Google Gemini, a simple button leading to the API key page would be much more convenient.
- I propose adding a link in the extension popup that would link to this [page](https://aistudio.google.com/app/apikey)

**Comment by apoorvsxna** [comment]
I'd like to take up this issue

**Comment by gitgoap** [comment]
@apoorvsxna it will be helpful to add this button
